### PR TITLE
Update contributors list.

### PR DESCRIPTION
**Pull request by portsmouth**
image

### CODE REVIEW

**Review by virtualzavie — APPROVED** [review]
I first thought it was inconsistent that Brecht van Lommel is sorted based on "van Lommel" while Eugene d'Eon is sorted based on "Eon".
But if I understand correctly [what Wikipedia says](https://en.wikipedia.org/wiki/Wikipedia:Categorization/Sorting_names), that's actually the proper way of sorting them.

**Review by jstone-lucasfilm — APPROVED** [review]
Ship it!

**Comment by portsmouth** [comment]
We should also thank Anton Palmqvist for contributing his example materials.

**Comment by virtualzavie** [comment]
Yes, if we could include them, that would look great.

**Pull request merged**
